name: IT Monitoring Watcher

on:
  workflow_dispatch:
  schedule:
    # UTC 0時 = JST 9時 に毎日実行
    - cron: '0 0 * * *'

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run IT_monitoring.py and save output
      run: |
        python IT_monitoring.py > result.md

    - name: Commit & push result
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add result.md
        git diff --staged --quiet || git commit -m "Update monitoring results"
        git push
